services:
  - type: web
    name: whatsapp-drive-sync
    env: python
    buildCommand: |
      mkdir -p user_credentials
      mkdir -p templates
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        sync: false
      - key: REDIS_URL
        value: redis://red-cujbjt52ng1s73b4garg:6379
    disk:
      name: user-storage
      mountPath: /opt/render/project/src/user_credentials
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true